name: notify

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, reopened ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: send_message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: |
            Um novo PR do back foi criado
            Veja https://github.com/wanderdasouza/sorting-hat-api/pulls/${{ github.event.number }}

